 name: Test Action Locally
 on:
   push:
     branches:
       - test_back
 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - name: Run Local Action
         uses: adobe/aio-cloudmanager-create-execution-action@v1.2.0
         with:
           CLIENTID: ${{ secrets.CM_CLIENT_ID }}
           CLIENTSECRET: ${{ secrets.CM_CLIENT_SECRET }}
           TECHNICALACCOUNTID: ${{ secrets.CM_TA_ID }}
           TECHNICALACCOUNTEMAIL: ${{ secrets.CM_TA_EMAIL }}
           IMSORGID: ${{ secrets.CM_ORG_ID }}
           KEY: ${{ secrets.CM_PRIVATE_KEY }}
           PIPELINEID: ${{ secrets.CM_PIPELINE_ID }}
           PROGRAMID: ${{ secrets.CM_PROGRAM_ID }}
           OAUTHENABLED: 'true'
